# Generated by Django 3.0.5 on 2021-03-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_insta_msg_replace_letters_replace_letters_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='replace_letters',
            name='options',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='replace_letters_options',
        ),
    ]
