# Generated by Django 3.0.5 on 2021-03-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210314_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='insta_output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='instence_start_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
